blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Snoww3d/jwst-data-analysis/blob/main/README.md
    about: Check the documentation before opening an issue
  - name: Security Vulnerabilities
    url: https://github.com/Snoww3d/jwst-data-analysis/blob/main/SECURITY.md
    about: Please report security vulnerabilities privately
